### ISSUE TITLE
1 out of 282 tests failed

### ISSUE THREAD

**Issue by cbjuju** [perl11/potion#106]
I built potion using the command `sudo make`. When I tried to test the build, I ran `make test`. 1 out of 282 tests failed saying that the recipe for the target `test` has failed. As far as I can tell two of the prerequisites of the target `test` are not available : 
```
test: pn libs test/api/potion-test${EXE} test/api/gc-test${EXE}
	test/runtests.sh -q
```
I cannot see anything called `pn` or `libs` in the directory containing the makefile, although there is a `lib`. Did I do something wrong ?

**Comment by rurban** [comment]
I think I haven't fixed the sort test yet. I wanted to change it completely to take a lambda block argument

**Comment by iacore** [comment]
I think this is fixed?

**Comment by rurban** [comment]
No, because sort is still not implemented as lambda, and thus the test still fails
