### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by TashaArvanitis** [perl11/potion#80]
I tried to follow the directions [here](http://fogus.github.io/potion/download.html) for installation, but ran into a problem, both when I downloaded the repo as a .zip file and when I cloned it. The full output from running `make` inside the `potion` directory:

```
Makefile:13: config.inc: No such file or directory
config.mak:276: config.inc: No such file or directory
MAKE config.inc
MAKE core/version.h
MAKE core/config.h
CC core/potion.opic -O0
CC core/asm.opic
CC core/ast.opic
CC core/compile.opic
CC core/contrib.opic
CC core/gc.opic
CC core/internal.opic
CC core/lick.opic
CC core/mt19937ar.opic
CC core/number.opic
CC core/objmodel.opic
CC core/primitive.opic
CC core/string.opic
CC bin/greg
GREG core/syntax.c
rule 'sig' defined but not used
CC core/syntax.opic
CC core/table.opic
CC core/vm.opic
CC core/callcc.opic -O0 +frame-pointer
CC core/file.opic
CC core/load.opic
CC core/vm-x86.opic
LD lib/libpotion.dylib
LINK bin/potion
STRIP bin/potion
strip:bin/potion: File format not recognized
make: *** [bin/potion] Error 1
```

From an unzipped version of the repository, I had the same problem, but with many `fatal: Not a git repository (or any of the parent directories): .git` errors thrown in before the `CC` stage. 

Am I doing something wrong? Thanks in advance for any help!

**Comment by rurban** [comment]
Since this uses libpotion.dylib I assume that's a mac, with a broken strip.
Please try `make STRIP=echo`

**Comment by rurban** [comment]
The `fatal: Not a git repository (or any of the parent directories): .git` are now fixed with the branch `no-git-85`.
Did `make STRIP=echo` fix your problem?

**Comment by TashaArvanitis** [comment]
Yes, `make STRIP=echo` fixed the installation (though `make test` still fails), and I seem to be able to run the examples.

**Comment by rurban** [comment]
Thanks. I merged some git fixes. The remaining issue with the release version is the libuv dependency.
